#!/bin/bash

source common.sh

# define the tests

testLift4(){
  logTO test_lift4.log
  goodCMD mcrl -tbf -regular -nocluster lift4.mcrl
  goodCMD lpo2lts-hre --workers=4 lift4.tbf lift4.gcf
  goodCMD sigmin-mpi --workers=4 --branching lift4.gcf lift4-b.gcf
  goodCMD ce-mpi --workers=4 lift4.gcf lift4-ce.gcf
  badCMD sigmin-mpi --workers=4 --branching-tcf lift4.gcf
  goodCMD sigmin-mpi --workers=4 --branching-tcf lift4-ce.gcf lift4-ce-b.gcf
  badCMD ltscmp-one -s lift4.gcf lift4-b.gcf
  badCMD ltscmp-one -s lift4.gcf lift4-ce.gcf
  goodCMD ltscmp-one -b lift4.gcf lift4-b.gcf
  goodCMD ltscmp-one -s lift4-b.gcf lift4-ce-b.gcf
  /bin/rm -rf lift4.tbf lift4*.gcf
}

testHefWrong(){
  logTO test_hef_wrong.log
  goodCMD mcrl -tbf -regular -nocluster hef_wrong.mcrl
  goodCMD lpo2lts-gsea -d hef_wrong.tbf --trace hef_wrong-trace.gcf --strategy=dfs
  goodCMD lts-tracepp -l hef_wrong-trace.gcf
  goodCMD lpo2lts-hre hef_wrong.tbf hef_wrong.gcf
  goodCMD sigmin-one -b hef_wrong.gcf
  goodCMD instantiator hef_wrong.tbf
  goodCMD ltstrans --rdwr hef_wrong.gcf hef_wrong-trans.aut
  goodCMD ltscmp -s hef_wrong-trans.aut hef_wrong.aut
  mustSay "Labeled transitions systems are equivalent"
  /bin/rm -rf hef_wrong.tbf hef_wrong*.gcf hef_wrong*.aut
}
#oneTimeTearDown(){
#    /bin/rm -f test.err
#}

# run them for specified output format
case $1 in
 txt)
    shift
    echo "outputting result as text"
    . shunit2.txt
 ;;
 xml)
    shift
    SHUNIT_OUTPUTDIR=.
    . shunit2.xml
 ;;
 *)
    echo "unknown output format, usage: $0 txt|xml"
 ;;
esac

