#!/bin/bash

source common.sh

# define the tests

testCreate(){
  logTO test_create.log
  goodCMD gcf --create test.gcf test-gcf shunit*
  goodCMD gcf -f -q -x --output=test.dir test.gcf
  badCMD  gcf -q -x --output=test.dir test.gcf
  compareFiles . test.dir test-gcf shunit2.*
  /bin/rm -rf test.dir
  goodCMD gcf --to-zip test.gcf test.zip
  goodCMD unzip -d test.dir test.zip
  compareFiles . test.dir test-gcf shunit2.*
  /bin/rm -rf test.gcf test.dir
  goodCMD gcf --from-zip test.zip test.gcf
  goodCMD gcf -f -q -x --output=test.dir test.gcf
  compareFiles . test.dir test-gcf shunit2.*
  /bin/rm -rf test.gcf test.dir test.zip
}

#oneTimeTearDown(){
#    /bin/rm -f test.err
#}

# run them for specified output format
case $1 in
 txt)
    shift
    echo "outputting result as text"
    . shunit2.txt
 ;;
 xml)
    shift
    SHUNIT_OUTPUTDIR=.
    . shunit2.xml
 ;;
 *)
    echo "unknown output format, usage: $0 txt|xml"
 ;;
esac

