# include the general include file which contains the functions
source lib/include.tcl
source lib/backends.tcl

puts "\n----------------------------------------------"
puts   "TESTING: Algorithmic backends for LPO language"
puts   "----------------------------------------------\n"


#cd into the test dir such that output files are placed here.
cd $subdir

# use the local uncluding file containing several procedures

# the number of threads to use in multithreaded backends
set num_threads 5

# lpo:
dict set langs lpo model "hef_wrong.tbf"
dict set langs lpo options mc "--procs=$num_threads"
dict set langs lpo exp_output "15557 states 27300 transitions"

set filter "{mc}"
set EXAMPLES_PATH "../../examples"

# find the available backends
set alg_be [ find_alg_backends $filter ]

# run the test for the ETF-frontend
run_test_for_alg_backends $alg_be $langs $backends
