# include the general include file which contains the functions
source lib/include.tcl
# use the backends include file containing several 
# procedures special for algorithmic backends
source lib/backends.tcl

#cd into the test dir such that output files are placed here.
cd $subdir

puts "\n----------------------------------------------"
puts   "TESTING: Algorithmic backends for LPO language"
puts   "----------------------------------------------\n"

# the number of threads to use in multithreaded backends
set num_threads 5

set langs [dict create]

# lpo defines
dict set langs lpo model "hef_wrong.tbf"
dict set langs lpo options mc "--procs=$num_threads"

dict set langs lpo exp_output "15557 states 27300 transitions"
set alg_be [ find_alg_backends "{dist,mc,seq}" ]
run_test_for_alg_backends $alg_be $langs $backends

# different output for symbolic tool:
dict set langs lpo exp_output "state space has 15557"
set alg_be [ find_alg_backends "{sym}" ]
run_test_for_alg_backends $alg_be $langs $backends


cd ".."
