# include the general include file which contains the functions
source $srcdir/lib/include.tcl
# use the nclude file containing several procedures
source $srcdir/lib/backends.tcl

#cd into the test dir such that output files are placed here.
if { [file exists $binpaths(out) ] != 1 } {
    file mkdir $binpaths(out)
}
cd $binpaths(out)

puts "\n-----------------------------"
puts   "TESTING: Algorithmic backend for the DVE language"
puts   "-----------------------------\n"

set langs [dict create]

# Language frontends:
# -------------------

set DVE_model "gear.1.dve"
compile_DVE $DVE_model

# dve:
dict set langs dve model "${DVE_model}2C"
dict set langs dve options mc

dict set langs dve exp_output "2689 states 3567 transitions"
set alg_be [ find_alg_backends "{dist,mc,seq}" ]
run_test_for_alg_backends $alg_be $langs $backends

# different output for symbolic tool:
dict set langs dve exp_output "state space has 2689"
set alg_be [ find_alg_backends "{sym}" ]
run_test_for_alg_backends $alg_be $langs $backends


cd ".."
