#!/bin/bash

# returns 0 when $1 > $2,
# 1 otherwise.

if [[ $1 == $2 ]]
then
    exit 1 
fi
IFS=.
i="" ver1=($1) ver2=($2)
# fill empty fields in ver1 with zeros
for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
do
    ver1[i]=0
done
for ((i=0; i<${#ver1[@]}; i++))
do
    if [[ -z ${ver2[i]} ]]
    then
        # fill empty fields in ver2 with zeros
        ver2[i]=0
    fi
    if ((10#${ver1[i]} > 10#${ver2[i]}))
    then
        exit 0
    fi
    if ((10#${ver1[i]} < 10#${ver2[i]}))
    then
        exit 1
    fi
done
exit 1
