# include the general include file which contains the functions
source $srcdir/lib/include.tcl

# use the local uncluding file containing several procedures
source $srcdir/lib/backends.tcl

#cd into the test dir such that output files are placed here.
if { [file exists $binpaths(out) ] != 1 } {
    file mkdir $binpaths(out)
}
cd $binpaths(out)

puts "\n----------------------------------------------"
puts   "TESTING: Algorithmic backends for ETF language"
puts   "----------------------------------------------\n"

# Language ETF-frontends:
# -------------------
set langs [dict create]
# a model per language
dict set langs etf model "gear.1.etf" 
dict set langs etf options mc

dict set langs etf exp_output "2689 states 3567 transitions"
set alg_be [ find_alg_backends "{dist,mc,seq}" ]
run_test_for_alg_backends $alg_be $langs $backends

# different output for symbolic tool:
dict set langs etf exp_output "state space has 2689"
set alg_be [ find_alg_backends "{sym}" ]
run_test_for_alg_backends $alg_be $langs $backends


cd ".."
