source $srcdir/lib/include.tcl

if { [file exists $binpaths(out) ] != 1 } {
    file mkdir $binpaths(out)
}
cd $binpaths(out)

puts "\n----------------------------------------------"
puts   "TESTING: LTL Algorithms"
puts   "----------------------------------------------\n"

set commands [dict create]

# TEST 16:

set strategies {"cndfs" "lndfs" "endfs" "endfs,lndfs" "endfs,endfs,ndfs" "ndfs" "ufscc"}

# anderson:
compile_DVE {"anderson.1.prop4.dve"}

foreach s $strategies {
    dict set commands test16_dve_mc_$s cmd "$binpaths(dve2lts-mc) --threads=2 \
    	--strategy=$s -s22 anderson.1.prop4.dve2C"
    dict set commands test16_dve_mc_$s exp "633945 states|unique states count:        633945"
}
dict set commands test_16_dve_seq cmd "$binpaths(dve2lts-seq) --strategy=scc \
	anderson.1.prop4.dve2C"
# This expected value is assumed to be the same as previous multicore results. This is untested!
dict set commands test_16_dve_seq exp "633945 states"


# p117
compile_promela {"p117.pml"}

foreach s $strategies {
    dict set commands test16_seq_$s cmd "$binpaths(prom2lts-mc) --threads=2 \
	--strategy=$s -s20 p117.pml.spins"
    dict set commands test16_seq_$s exp "354 states|unique states count:        354"
}
dict set commands test16_prom_seq cmd "$binpaths(prom2lts-seq) --strategy=scc \
					p117.pml.spins"
dict set commands test16_prom_seq exp "354 states"

# TEST 17:

# iprotocol
compile_DVE {"iprotocol.2.prop4.dve"}

foreach s $strategies {
    dict set commands test17_dve_mc_$s cmd "$binpaths(dve2lts-mc) --threads=2 \
	-s22 --strategy=$s iprotocol.2.prop4.dve2C"
    dict set commands test17_dve_mc_$s exp "Accepting cycle FOUND"
}
dict set commands test_17_dve_seq cmd "$binpaths(dve2lts-seq) --strategy=scc \
	iprotocol.2.prop4.dve2C"
dict set commands test_17_dve_seq exp "accepting cycle found"

# zune:
compile_promela {"zune.pml"}

foreach s $strategies {
    dict set commands test17_prom_mc_$s cmd "$binpaths(prom2lts-mc) --threads=2 \
	-s22 --strategy=$s zune.pml.spins"
    dict set commands test17_prom_mc_$s exp "Accepting cycle FOUND"
}
dict set commands test17_prom_seq cmd "$binpaths(prom2lts-seq) --strategy=scc \
					zune.pml.spins"
dict set commands test17_prom_seq exp "accepting cycle found"

# TEST 18:
compile_DVE {"iprotocol.2.dve"}

dict set commands test18_mc cmd "$binpaths(dve2lts-mc) --strategy=ndfs \
	-s22 iprotocol.2.dve2C \
	--ltl=$EXAMPLES_PATH/iprotocol.2.ltl"
dict set commands test18_mc exp "Accepting cycle FOUND"

# NOTE: the difference in the use of captitals in the expected output between this and previous test
dict set commands test18_seq cmd "$binpaths(dve2lts-seq) --strategy=scc \
	iprotocol.2.dve2C \
	--ltl=$EXAMPLES_PATH/iprotocol.2.ltl"
dict set commands test18_seq exp "accepting cycle found"


# TEST 19:
compile_DVE {"elevator.3.dve"}

dict set commands test19_mc cmd [subst "$binpaths(dve2lts-mc) --strategy=ndfs \
	-s22 elevator.3.dve2C \
	--ltl=$EXAMPLES_PATH/elevator.3.ltl"]
dict set commands test19_mc exp "495463 states"

dict set commands test19_seq cmd "$binpaths(dve2lts-seq) --strategy=scc \
	elevator.3.dve2C \
	--ltl=$EXAMPLES_PATH/elevator.3.ltl"
dict set commands test19_seq exp "495463 states"

foreach testcase [dict keys $commands] {
    set command [dict get $commands $testcase cmd]
    set exp [dict get $commands $testcase exp]

#    puts "$command"

    runmytest $testcase $command $exp
}


cd ".."
