# include the general include file which contains the functions
source $srcdir/lib/include.tcl
# use the nclude file containing several procedures
source $srcdir/lib/backends.tcl

#cd into the test dir such that output files are placed here.
if { [file exists $binpaths(out) ] != 1 } {
    file mkdir $binpaths(out)
}
cd $binpaths(out)

puts "\n-----------------------------"
puts   "TESTING: Algorithmic backends for Mcrl2"
puts   "-----------------------------\n"

# the number of threads to use in multithreaded backends
set num_threads 2

set langs [dict create]

# Language frontends:
# -------------------

# lps:
dict set langs lps model "ieee-11073.lps"
dict set langs lps options mc "--procs=$num_threads --mcrl2-rewriter=jitty"
dict set langs lps options dist "--mcrl2-rewriter=jitty"
dict set langs lps options seq "--mcrl2-rewriter=jitty"
dict set langs lps options sym "--mcrl2-rewriter=jitty"

dict set langs lps exp_output "831 states 2893 transitions"
set alg_be [ find_alg_backends "{dist,mc,seq}" ]
run_test_for_alg_backends $alg_be $langs $backends

# different output for symbolic tool:
dict set langs lps exp_output "state space has 831"
# below, disable the -g option, this fails in 201409.1, but fixed in newer SVN version.
dict set backends sym options {"-rga" ""}
set alg_be [ find_alg_backends "{sym}" ]
run_test_for_alg_backends $alg_be $langs $backends


cd ".."
