# include the general include file which contains the functions
source lib/include.tcl
# use the nclude file containing several procedures
source lib/backends.tcl

#cd into the test dir such that output files are placed here.
cd $subdir

puts "\n-----------------------------"
puts   "TESTING: Algorithmic backends for Mcrl2"
puts   "-----------------------------\n"

# the number of threads to use in multithreaded backends
set num_threads 5

set langs [dict create]

# Language frontends:
# -------------------

# lps:
dict set langs lps model "ieee-11073.lps"
dict set langs lps options mc "--procs=$num_threads"

dict set langs lps exp_output "1760 states 6583 transitions"
set alg_be [ find_alg_backends "{dist,mc,seq}" ]
run_test_for_alg_backends $alg_be $langs $backends

# different output for symbolic tool:
dict set langs lps exp_output "state space has 1760"
set alg_be [ find_alg_backends "{sym}" ]
run_test_for_alg_backends $alg_be $langs $backends


cd ".."
