source lib/include.tcl

cd $subdir

set commands [dict create]


# TEST 8:

dict set commands test8 cmd "$binpaths(dve2lts-sym) $EXAMPLES_PATH/gear.1.dve gear.1.etf"
dict set commands test8 exp "state space has 2689 (~2.69e+03) states, 1716 BDD nodes"

dict set commands test8_check cmd "$binpaths(etf2lts-seq) gear.1.etf"
dict set commands test8_check exp "2689 states 3567 transitions"


# TEST 9:

dict set commands test9_seq cmd "$binpaths(lps2lts-seq) $EXAMPLES_PATH/ieee-11073.lps model.gcf"
# TODO: unknown expected output since the tool crashes
dict set commands test9_seq exp "1760 states 6583 transitions"

dict set commands test9_dist cmd "$binpaths(lps2lts-dist) $EXAMPLES_PATH/ieee-11073.lps model.gcf"
# TODO: unknown expected output since the tool crashes
dict set commands test9_dist exp "1760 states 6583 transitions"


# TEST 10:

# TODO: Is there a need for a --thread=5 parameter?
dict set commands test10_mc cmd "$binpaths(prom2lts-mc) $EXAMPLES_PATH/p117.pml.spinja -d --trace=a.gcf"
# TODO: Unknown correct output since this tool crashes with a segmentation fault
dict set commands test10_mc exp ""

dict set commands test10_seq cmd "$binpaths(prom2lts-seq) $EXAMPLES_PATH/p117.pml.spinja -d --trace=a.gcf"
# TODO: Unknown correct output since this tool crashes with an illegal instruction
dict set commands test10_seq exp ""

# TODO: Got : ** error **: bad option: --trace=a.gcf (use --help for help)
dict set commands test10_dist cmd "$binpaths(prom2lts-dist) $EXAMPLES_PATH/p117.pml.spinja -d --trace=a.gcf"
# TODO: Unknown correct output since the above error
dict set commands test10_dist exp ""

dict set commands test10_sym cmd "$binpaths(prom2lts-sym) $EXAMPLES_PATH/p117.pml.spinja -d --trace=a.gcf"
# TODO: Unknown correct output since this tool crashes with a segmentation fault
dict set commands test10_sym exp ""

# TODO: Validate the traces of this test by using ltsmin-printtrace


# TEST 11:
# gcf is already tested and created in test 9.
#dict set commands test11_gcf cmd "$binpaths(lps2lts-seq) $EXAMPLES_PATH/ieee-11073.lps model.gcf"
#dict set commands test11_gcf exp ""

dict set commands test11_bcg cmd "$binpaths(lps2lts-seq) $EXAMPLES_PATH/ieee-11073.lps model.bcg"
dict set commands test11_bcg exp "1760 states 6583 transitions"

dict set commands test11_aut cmd "$binpaths(lps2lts-seq) $EXAMPLES_PATH/ieee-11073.lps model.aut"
dict set commands test11_aut exp "1760 states 6583 transitions"

dict set commands test11_fsm cmd "$binpaths(lps2lts-seq) $EXAMPLES_PATH/ieee-11073.lps model.fsm"
# TODO: Unknown correct output since the tool crashes with a segmentation fault
dict set commands test11_fsm exp "1760 states 6583 transitions"

dict set commands test11_dir cmd "$binpaths(lps2lts-seq) $EXAMPLES_PATH/ieee-11073.lps model.dir"
# TODO: Unknown correct output since the tool crashes with a segmentation fault
dict set commands test11_dir exp "1760 states 6583 transitions"

# compare the output to eachother

#TODO: selecting an appropriate comparing method, now just using "-b" because that one does not crash
dict set commands test11_check1 cmd "$binpaths(ltsmin-compare) -b model.gcf model.bcg"
dict set commands test11_check1 exp "LTSs are equivalent"

dict set commands test11_check2 cmd "$binpaths(ltsmin-compare) -b model.bcg model.aut"
dict set commands test11_check2 exp "LTSs are equivalent"

dict set commands test11_check3 cmd "$binpaths(ltsmin-compare) -b model.aut model.fsm"
dict set commands test11_check3 exp "LTSs are equivalent"

dict set commands test11_check4 cmd "$binpaths(ltsmin-compare) -b model.fsm model.dir"
dict set commands test11_check4 exp "LTSs are equivalent"

dict set commands test11_check5 cmd "$binpaths(ltsmin-compare) -b model.dir model.gcf"
dict set commands test11_check5 exp "LTSs are equivalent"


# TEST 12:

dict set commands test12_gcf cmd "$binpaths(lps2lts-dist) --procs=4 $EXAMPLES_PATH/ieee-11074.lps model_dist.gcf"
# TODO: Unknown correct output since the tool crashes with a segmentation fault
dict set commands test12_gcf exp ""

dict set commands test12_dir cmd "$binpaths(lps2lts-dist) --procs=4 $EXAMPLES_PATH/ieee-11074.lps model_dist.dir"
# TODO: Unknown correct output since the tool crashes with a segmentation fault
dict set commands test12_dir exp ""

# NOTE: The working of the following code has never been tested since no correct output was available
dict set commands test12_check cmd "$binpaths(ltsmin-compare) -b model_dist.dir model_dist.gcf"
dict set commands test12_check exp "LTSs are equivalent"


foreach testcase [dict keys $commands] {
    set command [dict get $commands $testcase cmd]
    set exp [dict get $commands $testcase exp]
    runmytest $testcase $command $exp
}

cd ".."
