# include the general include file which contains the functions
source $srcdir/lib/include.tcl

# use the local uncluding file containing several procedures
source $srcdir/lib/backends.tcl

#cd into the test dir such that output files are placed here.
if { [file exists $binpaths(out) ] != 1 } {
    file mkdir $binpaths(out)
}
cd $binpaths(out)

puts "\n----------------------------------------------"
puts   "TESTING: Algorithmic backends for PNML language"
puts   "----------------------------------------------\n"

# Language PNML-frontends:
# -------------------
set langs [dict create]
# a model per language
dict set langs pnml model "Philosophers-5.pnml" 

dict set langs pnml exp_output "243 states 945 transitions"
set alg_be [ find_alg_backends "{dist,mc,seq}" ]
run_test_for_alg_backends $alg_be $langs $backends

# different output for symbolic tool:
dict set langs pnml exp_output "state space has 243"
set alg_be [ find_alg_backends "{sym}" ]
run_test_for_alg_backends $alg_be $langs $backends


cd ".."
