# include the general include file which contains the functions
source lib/include.tcl
# use the nclude file containing several procedures
source lib/backends.tcl

#cd into the test dir such that output files are placed here.
cd $subdir

puts "\n-----------------------------"
puts   "TESTING: Algorithmic backends"
puts   "-----------------------------\n"

# the number of threads to use in multithreaded backends
set num_threads 5

set langs [dict create]

# Language frontends:
# -------------------

# dve:
dict set langs dve model "gear.1.dve"
dict set langs dve options mc "--threads=$num_threads"
dict set langs dve exp_output "2689 states 3567 transitions"

# prom:
set prom_model "fgs.promela"
dict set langs prom model [subst "$prom_model.spinja"]
# list with commands to be executed before the language tests. This can be used to generate models.
dict set langs prom precommands [subst {"$binpaths(spinjal) $EXAMPLES_PATH/$prom_model" "mv $prom_model.spinja $EXAMPLES_PATH/"}]
dict set langs prom options mc "--threads=$num_threads"
dict set langs prom exp_output "242 states 3388 transitions"

# lps:
dict set langs lps model "ieee-11073.lps"
dict set langs lps options mc "--procs=$num_threads"
dict set langs lps exp_output "1760 states 6583 transitions"

# opaal:
dict set langs opaal model "fischer4.xml"
dict set langs opaal options mc "--threads=$num_threads"
dict set langs opaal exp_output "268 states 552 transitions"

# pbes:
dict set langs pbes model "brp-nodeadlock.pbes"
dict set langs pbes options mc "--procs=$num_threads"
dict set langs pbes exp_output "10548 states 12168 transitions"

set filter "{mc}"

set alg_be [ find_alg_backends $filter ]

run_test_for_alg_backends $alg_be $langs $backends


cd ".."
