# include the general include file which contains the functions
source lib/include.tcl

# use the local uncluding file containing several procedures
source lib/backends.tcl

#cd into the test dir such that output files are placed here.
cd $subdir

puts "\n----------------------------------------------"
puts   "TESTING: Algorithmic backends for ETF language"
puts   "----------------------------------------------\n"


# the number of threads to use in multithreaded backends
set num_threads 5

# Language ETF-frontends:
# -------------------
set langs [dict create]
# a model per language
# This is a required field. Whitout it, the language is skipped
dict set langs etf model "gear.1.etf" 
# for each language frontend optional parameters per backend
dict set langs etf options mc "--threads=$num_threads"
# the expected result for a pass
dict set langs etf exp_output ""

# Wich backends are we performing the ETF language tests on?
set filter "{mc}"

# find the available backends
set alg_be [ find_alg_backends $filter ]

# run the test for the ETF-frontend
run_test_for_alg_backends $alg_be $langs $backends

cd ".."
