source $srcdir/lib/include.tcl

if { [file exists $binpaths(out) ] != 1 } {
    file mkdir $binpaths(out)
}
cd $binpaths(out)


puts "\n----------------------------------------------"
puts   "TESTING: DFS_FIFO"
puts   "----------------------------------------------\n"


set commands [dict create]

compile_promela {"i4" "TimingWithoutTimeout9OnTheFlynessShallow.promela"}

dict set commands test13_mc cmd "$binpaths(prom2lts-mc) --strategy=dfsfifo -v i4.spins --threads=2"
dict set commands test13_mc exp "Elements: 78977"

dict set commands test13_por cmd "$binpaths(prom2lts-mc) --strategy=dfsfifo --por -v i4.spins --threads=2"
dict set commands test13_por exp "Elements: 30373"

dict set commands test14_mc cmd "$binpaths(prom2lts-mc) --strategy=dfsfifo TimingWithoutTimeout9OnTheFlynessShallow.promela.spins --threads=2"
dict set commands test14_mc exp "Non-progress cycle FOUND"

dict set commands test14_por cmd "$binpaths(prom2lts-mc) --por --strategy=dfsfifo TimingWithoutTimeout9OnTheFlynessShallow.promela.spins --threads=2"
dict set commands test14_por exp "Non-progress cycle FOUND"

foreach testcase [dict keys $commands] {
    set command [dict get $commands $testcase cmd]
    set exp [dict get $commands $testcase exp]
    runmytest $testcase $command $exp
}


cd ".."
